name: Build and package VSCode extension

on:
    push:
        branches:
            - main
    pull_request: # Added pull_request event
        branches:
            - main
    workflow_dispatch:

jobs:
    extension:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - name: Build extension
              run: |
                  npm install
                  npm run prettier-check
                  npm run type-check
                  npm run compile
                  npm run lint

            - name: Package extension
              run: |
                  npx @vscode/vsce package

            - name: Upload VSIX as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vsix
                  path: '*.vsix'